# Generated by Django 2.1.1 on 2018-09-05 02:46

import core.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Car',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('series', models.CharField(max_length=100)),
                ('price', models.IntegerField()),
                ('enginesize', models.CharField(max_length=10)),
                ('fuelsystem', models.CharField(max_length=100)),
                ('tankcapacity', models.CharField(max_length=100)),
                ('power', models.CharField(max_length=10)),
                ('seats', models.IntegerField()),
                ('standardtransmission', models.CharField(max_length=100)),
                ('bodyType', models.CharField(max_length=100)),
                ('drive', models.CharField(max_length=50)),
                ('wheelbase', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=30)),
                ('address', models.CharField(max_length=200)),
                ('birthday', models.DateField()),
                ('occupation', models.CharField(choices=[(core.models.Occupation('Labour'), 'Labour'), (core.models.Occupation('Manager'), 'Manager'), (core.models.Occupation('Retiree'), 'Retiree'), (core.models.Occupation('Nurse'), 'Nurse'), (core.models.Occupation('Researcher'), 'Researcher'), (core.models.Occupation('Other'), 'Other')], max_length=20)),
                ('gender', models.CharField(choices=[(core.models.Gender('Male'), 'Male'), (core.models.Gender('Female'), 'Female')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=30)),
                ('city', models.CharField(max_length=200)),
                ('state', models.CharField(choices=[(core.models.State('Queensland'), 'Queensland'), (core.models.State('New South Wales'), 'New South Wales'), (core.models.State('Victoria'), 'Victoria'), (core.models.State('Australian Capital Territory'), 'Australian Capital Territory'), (core.models.State('Tasmania'), 'Tasmania'), (core.models.State('Northern Territory'), 'Northern Territory'), (core.models.State('South Australia'), 'South Australia'), (core.models.State('Western Australia'), 'Western Australia')], max_length=40)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time', models.DateTimeField()),
                ('type', models.CharField(choices=[(core.models.TransactionType('Pickup'), 'Pickup'), (core.models.TransactionType('Return'), 'Return')], default='Pickup', max_length=10)),
                ('car', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Car')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Customer')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Store')),
            ],
        ),
    ]
